#!/bin/sh
python ../main.py \
    --model 'DenoiseLCALGNCNN' \
    --task 'CIFAR10' \
    --channels 512 \
    --kernels 5 \
    --pools 'ammm' \
    --strides 1  \
    --paddings 1  \
    --fc 10 \
    --sparse-layers 0 \
    --inhibitstrength 1.0 \
    --lambdas 0.1 \
    --competitiontype 'feature_inner_products' \
    --comp-syn-constraints 'rowunitnorm,zerodiag,transposesymmetric' \
    --optim 'sgd' \
    --mmt 0.9 \
    --lrs 0.25 0.1 \
    --lr-decay \
    --wds 3e-4 3e-4 3e-4 3e-4 3e-4 \
    --act 'my_hard_sig' \
    --todo 'train' \
    --betas 0.0 0.5 \
    --thirdphase \
    --T1 250 \
    --T2 25 \
    --mbs 128 \
    --loss 'mse' \
    --data-aug \
    --save  \
    --device 1 \
    --seed $1 \
    --epochs 120 \
    --tensorboard \
    --dt 0.25 \
